export enum Permission  {
	VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
	CREATE_TRANSACTIONS = 'CREATE_TRANSACTIONS',
	EDIT_TRANSACTIONS = 'EDIT_TRANSACTIONS',
	DELETE_TRANSACTIONS = 'DELETE_TRANSACTIONS',
	EXPORT_REPORTS = 'EXPORT_REPORTS',
	MANAGE_USERS = 'MANAGE_USERS',
	MANAGE_BUDGETS = 'MANAGE_BUDGETS',
}
