export const pricingTiers = [
  {
    id: 1,
    title: 'Free',
    monthlyPrice: 0,
    buttonText: 'Get started for free',
    popular: false,
    inverse: false,
    features: [
      'Up to 3 financial accounts',
      'Manual transaction entry',
      'Basic expense tracking',
      'Single budget setup',
      'Basic charts and reports',
      'Email support',
    ],
  },
  {
    id: 2,
    title: 'Pro',
    monthlyPrice: 12,
    buttonText: 'Sign up now',
    popular: true,
    inverse: true,
    features: [
      'Up to 10 financial accounts',
      'Bank account syncing',
      'Recurring transactions',
      'Custom spending categories',
      'Advanced charts and analytics',
      'Multiple budgets',
      'Export to CSV/PDF',
      'Email and chat support',
    ],
  },
  {
    id: 3,
    title: 'Business',
    monthlyPrice: 25,
    buttonText: 'Sign up now',
    popular: false,
    inverse: false,
    features: [
      'Unlimited financial accounts',
      'Team collaboration',
      'Audit logs',
      'Multi-currency support',
      'Custom tax reports',
      'Role-based access control',
      'Custom dashboards',
      'API access',
      'Advanced security features',
      'Priority support',
    ],
  },
];
